# This is a basic workflow to help you get started with Actions

name: Deploy to Aliyun OSS

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 打包任务
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 拉取代码
    - uses: actions/checkout@v2
    # 安装依赖
    - run: npm install
    # 打包
    - run: npm run build --if-present
    # 测试
    - run: npm test
      env: 
        CI: true
  oss:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm install
      # 打包
      - run: npm run build --if-present
      - uses: manyuanrong/setup-ossutil@v1.0
        with:
          endpoint: "oss-cn-beijing.aliyuncs.com"
          access-key-id: ${{secrets.ACCESS_KEY_ID}}
          access-key-secret: ${{secrets.ACCESS_KEY_SECRET}}
      # 清空已经存在的文件
      - run: ossutil rm -rf oss://ssrcoder-controls/*
      # 将dist目录下的文件复制到oss中
      - run: ossutil cp -rf ./dist oss://ssrcoder-controls/
        
